spring.application.name=DrbMVP

spring.datasource.url=jdbc:postgresql://localhost:5432/drbdb
spring.datasource.username=postgres
spring.datasource.password=rost
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

springdoc.swagger-ui.path=/swagger-ui.html

spring.security.user.name=admin
spring.security.user.password=admin

jwt.secret=your-very-secret-key-minimum-32-characters-long
jwt.expiration=86400000