spring.application.name=DrbMVP

spring.datasource.url=jdbc:postgresql://localhost:5432/drbdb
spring.datasource.username=postgres
spring.datasource.password=rost
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
